@isTest
public class DeleteDemoApex10 {
private Integer num;
    
    @isTest
   public static void helloMethod() {

        System.debug('Change Hello DemoApex11 Basic Pipeline GitHub Salesforce QA Team Feature Back Merge Validation Test 30/05/2026');
    

    }
    
    public static testMethod void testNewMethod() {
        System.debug('Change Hello DemoApex10 testing QA 235 Basic ');
    }
}