@isTest
public class DeleteDemoApex10 {
private Integer num;
    
    @isTest
   public static void helloMethod() {

        System.debug('Change Hello DemoApex11 Basic Pipeldsadsaine GitHub Salesforce QA Team Featurdsadae Back Merge Validation Test 31/08/2026');
    

    }
    
    public static testMethod void testNewMethod() {
        System.debug('Change Hello DemoApex10 dasdastesting QA 235 Basic ');
    }
}